version: '3.8'

services:
  whatspro:
    build: .
    restart: unless-stopped
    depends_on:
      - redis_local
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis_local:6379
      - NODE_ENV=production
    volumes:
      - whatsapp_auth:/app/whatsapp_auth

  redis_local: # <--- МІНЕ! Осы сөздің алдында міндетті түрде 2 бос орын (пробел) болуы керек.
    image: redis:7-alpine
    restart: always
    volumes:
      - whatspro_redis_data:/data

volumes:
  whatsapp_auth:
  whatspro_redis_data:
