version: '3.8'
services:
  whatspro:
    build: .
    restart: unless-stopped
    depends_on:
      - redis_local
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis_local:6379  # Өз ішіндегі Redis-ке қосылады
      - NODE_ENV=production
      # ... қалғандары ...
    volumes:
      - whatsapp_auth:/app/whatsapp_auth

  redis_local: # WhatsPro үшін жеке Redis
    image: redis:7-alpine
    restart: always

volumes:
  whatsapp_auth:
